"use client";

import KPIDashboard, { WeekData } from "@/components/KPIDashboard";

const weeksAsc: WeekData[] = [
  { week: 21, dates: "Jul 6–10", status: "complete", label: "ZCC-Freshdesk Architecture Finalized", stats: { pipelineUSD: 0, assetsCreated: 2, rescopings: 0, insightsFiled: 2, formalHandoffs: 0 }, contributions: { revenue: ["ZCC-to-Freshdesk-to-Salesforce ticketing architecture finalized with Max — the case-management backbone the Support Line’s lead-generation pipeline depends on", "IFRS Zoom migration count audit kicked off against production data, setting up the completeness check Fan’s team needs before Kaltura decommission", "Mithun’s Workato workspace access upgraded from “No access” to admin, clearing the blocker that had stalled ZCC integration work since Support Line launch"], preSales: ["Two-recipe Workato integration pattern documented (engagement-start Salesforce upsert + wrap-up Freshdesk ticket update via engagement_id correlation) — reusable template for future ZCC-CRM integrations", "FreshDesk connector action catalog mapped (14 actions, 4 triggers) as reference for the next ticketing integration build"], clientOutcomes: ["Caught the wrap-up webhook’s missing brief/disposition fields during architecture review — before implementation, not after a broken client-facing rollout", "Max’s existing recipe preserved untouched as a reference pattern while the production-ready version is built alongside it, avoiding disruption to his in-flight work", "Zero re-scopings across active engagements this week"], product: ["Discovered the ZCC “engagement_wrap_up_ended” webhook payload lacks brief text and disposition fields — invalidating the assumed architecture and requiring a new HTTP-fetch step", "IFRS video-count script rebuilt to query production Postgres directly (via Vercel-pulled credentials) instead of local/test data, for an accurate migration reconciliation baseline"], delivery: ["ZCC Flow Builder’s engagement-start HTTP Call scoped for re-pointing to the new Workato endpoint inside the live “Max Test – Web Chat to Video” flow (v15, published)", "IFRS reconciliation audit script stood up against production data, laying the groundwork for the full gap analysis completed the following week"] } },
  { week: 22, dates: "Jul 13–17", status: "current", label: "AI10 Live, IFRS Gaps Surfaced", stats: { pipelineUSD: 0, assetsCreated: 4, rescopings: 0, insightsFiled: 4, formalHandoffs: 2 }, contributions: { revenue: ["Coupa Goldcast-to-Zoom Webinars Plus migration proposal built and priced — $13K video migration (~50 videos) plus regional training, event setup, and live production, $26.2K total program investment", "Apex Technical implementation proposal in progress at $29K, adapting the Okta migration-plan template to include pricing and an instructional-hours breakdown", "Okta’s signed $15K CircleHD engagement stayed on track; corrected its delivery playbook this week rather than reopening scope"], preSales: ["Coupa one-pager built end-to-end with real Goldcast and Zoom Webinars Plus logo assets (sourced, resized, cleaned) rather than placeholder branding", "Apex Technical proposal drafted from the Okta implementation-plan template, adding a pricing section the template didn’t previously support", "Zoom OAuth Meeting Automation skill packaged as a reusable capability for future bulk meeting-provisioning engagements", "AI10 meeting-automation tooling built (Excel parser, payload builder, orchestration script) — reusable pattern for any future bulk Zoom meeting setup from a spreadsheet"], clientOutcomes: ["AI10 IAA (American Idol S10 auditions): 21 Main Room meetings plus 1 Winner’s Circle meeting created and verified live for CastItReach ahead of the production start", "IFRS reconciliation surfaced 828 entries that never received Zoom IDs and 13 videos present in Kaltura but missing from the Zoom mapping file — caught before the client’s final report, not after", "Zero re-scopings across active engagements this week"], product: ["Zoom Server-to-Server OAuth confirmed unable to create meetings despite documentation and OE Central precedent — General Apps used as a workaround, escalated as a platform inconsistency", "Zoom AI Companion confirmed unavailable for ISV account types and unsupported in breakout rooms — deferred rather than blocking the AI10 timeline", "Migration sync gap discovered: 28 of 749 API-migrated videos not appearing in the events portal — a Zoom-side platform bug flagged for escalation, not a migration failure", "IFRS entity-level audit found 11 of 13 unmapped videos have source flavors but were never migrated — recent June production content requiring a supplemental migration pass"], delivery: ["AI10 meeting spreadsheet fully populated and handed to Kara for the CastItReach team’s Google Sheet — production-ready ahead of audition days", "Flagged General OAuth app security exposure to Max immediately rather than waiting for the October 7 wrap, since the apps sit in a shared Zoom account alongside other OE clients", "Okta migration playbook corrected (removed an incorrect CircleHD service-account task) and PDF regenerated before further client use"] } },
];

export default function SEKPIDashboardQ3() {
  return <KPIDashboard quarterLabel="Q3" dateRangeLabel="July – September 2026" weeksAsc={weeksAsc} backHref="/reports/q3" />;
}
