"use client";

import KPIDashboard, { WeekData } from "@/components/KPIDashboard";

const weeksAsc: WeekData[] = [
  { week: 21, dates: "Jul 6–10", status: "complete", label: "Okta CircleHD Signed, Pre-Migration Process Built", stats: { pipelineUSD: 15000, assetsCreated: 2, rescopings: 0, insightsFiled: 5, formalHandoffs: 0 }, deals: [{ name: "Okta CircleHD-to-ZVM migration", amount: 15000, status: "confirmed" }], contributions: { revenue: ["Okta signed a $15K CircleHD-to-Zoom-Video-Management migration, with kickoff and technical discovery already underway", "Indeed's ZVM upload path fully validated end-to-end (video, metadata, channel placement), clearing the last blocker before the migration script ships", "IFRS's Kaltura offboarding date locked to a shared calendar hold, protecting the account from a last-minute access-loss scramble"], preSales: ["Built a reusable pre-migration discovery report template (entry counts, ownership mapping, tag/caption limits, embed codes) live with Max — now standard tooling for every future Kaltura migration", "Pulled real Indeed account metrics via Claude (6,976 entries, 21,935 users, 228 categories) to seed the new discovery report", "Sourced an evidenced target-account list and demoed the ROI calculator for new EMEA rep Jacob's competitive outbound motion"], clientOutcomes: ["Diagnosed and fixed Indeed's ZVM app clips-scope permission error before it became a client-visible blocker", "Declined to formally re-scope or charge IFRS for an out-of-scope video-pull request, protecting the relationship while looping Zoom in for visibility", "Zero re-scopings across active engagements this week"], product: ["Filed ZCM tickets 182, 183, 187, and 188 covering the pre-migration report build and IFRS final-migration work", "Escalated an IFRS video-display discrepancy (visible in Zoom's cloud recording storage but not the events platform) to Zoom's Stefan and Fan for engineering review", "Surfaced the Zoom Clips API's missing clip-management role permission as a reusable fix for any future ZVM integration app", "Confirmed Workato's MCP connection is live end-to-end, unlocking natural-language recipe building for the Contact Center integration"], delivery: ["Settled the Contact Center's Freshdesk/Salesforce integration architecture on a single Workato-webhook design instead of splitting logic across the agent platform", "Migration bot assessed at roughly 50% complete; flagged for reprioritization toward an end-of-month MVP given two concurrent live migrations", "Okta CircleHD kickoff scoped a Tuesday 9am recurring cadence and late-September production deadline ahead of the Octane conference"] } },
  { week: 22, dates: "Jul 13–17", status: "current", label: "AI10 Live, IFRS Gaps Surfaced", stats: { pipelineUSD: 0, assetsCreated: 4, rescopings: 0, insightsFiled: 4, formalHandoffs: 2 }, contributions: { revenue: ["Coupa Goldcast-to-Zoom Webinars Plus migration proposal built and priced — $13K video migration (~50 videos) plus regional training, event setup, and live production, $26.2K total program investment", "Apex Technical implementation proposal in progress at $29K, adapting the Okta migration-plan template to include pricing and an instructional-hours breakdown", "Okta’s signed $15K CircleHD engagement stayed on track; corrected its delivery playbook this week rather than reopening scope"], preSales: ["Coupa one-pager built end-to-end with real Goldcast and Zoom Webinars Plus logo assets (sourced, resized, cleaned) rather than placeholder branding", "Apex Technical proposal drafted from the Okta implementation-plan template, adding a pricing section the template didn’t previously support", "Zoom OAuth Meeting Automation skill packaged as a reusable capability for future bulk meeting-provisioning engagements", "AI10 meeting-automation tooling built (Excel parser, payload builder, orchestration script) — reusable pattern for any future bulk Zoom meeting setup from a spreadsheet"], clientOutcomes: ["AI10 IAA (American Idol S10 auditions): 21 Main Room meetings plus 1 Winner’s Circle meeting created and verified live for CastItReach ahead of the production start", "IFRS reconciliation surfaced 828 entries that never received Zoom IDs and 13 videos present in Kaltura but missing from the Zoom mapping file — caught before the client’s final report, not after", "Zero re-scopings across active engagements this week"], product: ["Zoom Server-to-Server OAuth confirmed unable to create meetings despite documentation and OE Central precedent — General Apps used as a workaround, escalated as a platform inconsistency", "Zoom AI Companion confirmed unavailable for ISV account types and unsupported in breakout rooms — deferred rather than blocking the AI10 timeline", "Migration sync gap discovered: 28 of 749 API-migrated videos not appearing in the events portal — a Zoom-side platform bug flagged for escalation, not a migration failure", "IFRS entity-level audit found 11 of 13 unmapped videos have source flavors but were never migrated — recent June production content requiring a supplemental migration pass"], delivery: ["AI10 meeting spreadsheet fully populated and handed to Kara for the CastItReach team’s Google Sheet — production-ready ahead of audition days", "Flagged General OAuth app security exposure to Max immediately rather than waiting for the October 7 wrap, since the apps sit in a shared Zoom account alongside other OE clients", "Okta migration playbook corrected (removed an incorrect CircleHD service-account task) and PDF regenerated before further client use"] } },
];

export default function SEKPIDashboardQ3() {
  return <KPIDashboard quarterLabel="Q3" dateRangeLabel="July – September 2026" weeksAsc={weeksAsc} backHref="/reports/q3" />;
}
